### ISSUE TITLE
rpm conflict with liveme tools

### ISSUE THREAD

**Issue by TuxNuX** [thecoder75/lamd#10]
HI,
I have conflict with the rpm installation

> the file /usr/lib/.build-id/bb/e5384c7ef7abee250ccc3090b0c7e99cf394a5 of the lamd-3.1.4-1.x86_64  conflicts with the liveme-pro-tools-1.332.20190312-1.x86_64 package file

installation be possible with option rpm "--force" but the conflict is not normal and must be repaired I think

download be completely bugged
![Screenshot_20190317_171241](https://user-images.githubusercontent.com/17123357/54494286-c6fb3b00-48d8-11e9-9870-0260cadd4a17.png)
![Screenshot_20190317_171224](https://user-images.githubusercontent.com/17123357/54494287-c793d180-48d8-11e9-848e-b1e5cdecf700.png)
![Screenshot_20190317_171207](https://user-images.githubusercontent.com/17123357/54494288-c793d180-48d8-11e9-8056-259ee9c2b434.png)
![Screenshot_20190317_171148](https://user-images.githubusercontent.com/17123357/54494289-c793d180-48d8-11e9-9db2-0238f64d5460.png)
![Screenshot_20190317_171123](https://user-images.githubusercontent.com/17123357/54494290-c793d180-48d8-11e9-8c87-446102b0d4e2.png)
![Screenshot_20190317_171055](https://user-images.githubusercontent.com/17123357/54494291-c82c6800-48d8-11e9-8d2b-4cb56159ba64.png)
same probleme with old version

**Comment by thecoder75** [comment]
That bug was addressed by [this commit](https://github.com/thecoder75/lamd/commit/eefd64a76e5b01c8804ac6bc24dee1b46352d9d5) and was included in the latest build.

**Comment by thecoder75** [comment]
As far as the conflict goes, that I'm stumped on as to why its flagging a conflict during installation.  May be due to both apps using Electron or something.

**Comment by TuxNuX** [comment]
> Ce bogue a été corrigé par [ce commit](https://github.com/thecoder75/lamd/commit/eefd64a76e5b01c8804ac6bc24dee1b46352d9d5) et a été inclus dans la dernière version.

Hi,
I have all these bug with the latest version
I tried with the GIT version and the same problems

![Screenshot_20190321_184023-1](https://user-images.githubusercontent.com/17123357/54773266-7e5dbd80-4c09-11e9-8612-ace9933c38cb.png)
