### ISSUE TITLE
Error: ENOENT while downloading some replays

### ISSUE THREAD

**Issue by camoulin** [thecoder75/lamd#11]
i get such error in LAMD when a download is triggered: 
Uncaught Exception:
                      Error: ENOENT: no such file or directory, open '/****/lmt/lamd_temp/***_start_0/end/467179/****_20190406032552_01ws0000000.ts'

probably rooted in the new naming of the .ts file segments. the slashes may be mis-interpreted as sub-folder while saving the local copy.

**Comment by thecoder75** [comment]
This issue was addressed by this [commit](https://github.com/thecoder75/lamd/commit/eefd64a76e5b01c8804ac6bc24dee1b46352d9d5).

**Comment by chickenmango1** [comment]
I have this error as well with the latest version.  Help?
