### ISSUE TITLE
Error ENOENT

### ISSUE THREAD

**Issue by chickenmango1** [thecoder75/lamd#12]
Error ENOENT when attempting to DL

**Comment by thecoder75** [comment]
Without any details on the error message or a screen shot of it, no assistance can be provided.

**Comment by chickenmango1** [comment]
Sorry for the lack of detail.  Im using Windows 10 see screenshot of error below.  Please let me know if you need additional detail. 
![errrrrrrrrrr](https://user-images.githubusercontent.com/40177473/56081265-55c87e00-5dd9-11e9-93e2-14d273696c53.PNG)

**Comment by thecoder75** [comment]
Thank you for the info.  This issue has been resolved now in the 3.1.5 release being built right now.

**Comment by chickenmango1** [comment]
Thanks.  I have a few suggestions for improvements hopefully this is an appropriate place to list them.
1. Make a toggle button to ignore or not ignore live broadcasts. 
2. Ability to scan more frequently than 30 minutes would be nice.  Every 5 minutes would be great.
3. Ignore broadcasts that have already been downloaded.
4.  Keep up the great work!
